### ISSUE TITLE
Missing tag/release for v0.5.2

### ISSUE THREAD

**Issue by docwhat** [chef/knife-push#29]
FYI: You're missing the git tag (and github release) for `knife-push` v0.5.2.

**Comment by manderson26** [comment]
Added the tag (and one for master at v0.6.0
Thanks for pointing that out. Looking at putting together releases shortly.

**Comment by manderson26** [comment]
And releases added. Thanks again for the report.

**Comment by docwhat** [comment]
@manderson26 Hey! Thanks for the quick fix, but I noticed that you released/tag v0.6.0 but you didn't upload it to [rubygems.org](https://rubygems.org/gems/knife-push).
