### ISSUE TITLE
undefined local variable or method `ui' for Chef::Knife::JobHelpers:Module

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/knife-push#33]
Calls to `ui.error` aren't working. It looks like these need to be called by `Chef::Knife.ui.error` instead.

https://github.com/chef/knife-push/blob/v0.9.0/lib/chef/knife/job_helpers.rb#L31

https://github.com/chef/knife-push/blob/v0.9.0/lib/chef/knife/job_helpers.rb#L40

https://github.com/chef/knife-push/blob/v0.9.0/lib/chef/knife/job_helpers.rb#L116

https://github.com/chef/knife-push/blob/v0.9.0/lib/chef/knife/job_helpers.rb#L126

https://github.com/chef/knife-push/blob/v0.9.0/lib/chef/knife/job_start.rb#L87

**Comment by klausyoum** [comment]
I hope my small report to improve knife-push quality. :) If fixed, I will check it again.

**Comment by juliandunn** [comment]
I can no longer reproduce this with `knife-push 1.0.2`. I'll close this for now - please reopen if it's still happening with that version.
