### ISSUE TITLE
Push releases to rubygems

### ISSUE THREAD

**Issue by scalp42** [chef/knife-push#37]
[Has not been updated in a while](https://rubygems.org/gems/knife-push), would be great if it could be sync'd with Github :pray: 

Thanks in advance :innocent:

**Comment by Tech356** [comment]
I just hit this issue too. Updating rubygems would be good.

**Comment by spuder** [comment]
I also ran into this. There is a major bug that has been fixed in the pre-release. #41

**Comment by chefsalim** [comment]
RubyGems updated with release v1.0.0
