### ISSUE TITLE
ArgumentError when calling knife job output 

### ISSUE THREAD

**Issue by klausyoum** [chef/knife-push#47]
Dear knife-push contributors,

I also met an ArgumentError when calling knife job output. It may be related with https://github.com/chef/knife-push/issues/41.

~/products/se$ knife job output 413c057eb8f84f82dba0c7fa868b47d0 test --channel stdout -VV
INFO: Using configuration from /home/chef/products/se/.chef/knife.rb
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http.rb:109:in `get': wrong number of arguments (3 for 1..2) (ArgumentError)
        from /home/chefadmin/.chefdk/gem/ruby/2.1.0/gems/knife-push-1.0.1/lib/chef/knife/job_output.rb:36:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:219:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/knife.rb:148:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/knife:25:in `<top (required)>'
        from /opt/chefdk/bin/knife:49:in `load'
        from /opt/chefdk/bin/knife:49:in `<main>'

To resolve this issue, I modifed knife-push/lib/chef/knife/job_output.rb at my local machine.

**job = rest.get_rest(uri, false, {"Accept"=>"application/octet-stream"})
=>
job = rest.get_rest(uri, {"Accept"=>"application/octet-stream"})**

If possible, could you fix this issue in knife-push clearly?
Thanks in advance.

**Comment by klausyoum** [comment]
For your information, following lines show my chef packages version.

~/git/knife-push$ chef -v
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0

~/git/knife-push$ knife -v
Chef: 12.8.1

**Comment by agshah** [comment]
Hi, 
I too am running into this error, ERROR: ArgumentError: wrong number of arguments (3 for 1..2)

 I tried the above workaround to job_output.rb. Now I get below error. Please help.

D:\learn-chef\chef-repo>knife job output 717c0a2d1dea1fdc2b69b4d00def7977 node1 --channel stdout
ERROR: The object you are looking for could not be found
Response: <HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD><BODY><H1>Not Found</H1
>The requested document was not found on this server.<P><HR><ADDRESS>mochiweb+we
bmachine web server</ADDRESS></BODY></HTML>

D:\learn-chef\chef-repo>

**Comment by agshah** [comment]
this is the error that I now get:

D:\learn-chef\chef-repo>knife job output 717c0a2d1dea1fdc2b69b4d00def7977 node1 --channel stdout
ERROR: The object you are looking for could not be found
Response: <HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD><BODY><H1>Not Found</H1
>The requested document was not found on this server.<P><HR><ADDRESS>mochiweb+we
bmachine web server</ADDRESS></BODY></HTML>

D:\learn-chef\chef-repo>

**Comment by agshah** [comment]
I ran with -VV option and here is the info, kindly advise.

D:\learn-chef\chef-repo>knife job output 717c0a2d1dea2c4ee0af483073e792ec node1
 --channel stdout -VV
INFO: Using configuration from D:/learn-chef/chef-repo/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as agshah
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Using www-proxy.env.com:80 for proxy
DEBUG: Initiating GET to https://node1/organizations/winprod/pu
shy/jobs/717c0a2d1dea2c4ee0af483073e792ec/output/node1/stdout
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/octet-stream
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: agshah
DEBUG: X-OPS-TIMESTAMP: 2016-08-02T22:44:08Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: gmNhjzBDuK3yBIEjyaDowKmYdMffcjxfjcpyZki4Hxyx0Rd/1u
69JdCnHPnT
DEBUG: X-OPS-AUTHORIZATION-2: OxtSBDNgfXxnHkWDeaKVZZJyr6M5JPVxd0ASVVr4MqODWjZ53r
1ki5EeI1JR
DEBUG: X-OPS-AUTHORIZATION-3: zHTYt8XpNOKNJWBK91Ux8LWA3Oduke6yTd4D013nICiAfOgtxE
2mwrR5srz+
DEBUG: X-OPS-AUTHORIZATION-4: ARvrlvSUivtxE5yRpaLc8e3ToDqBKbFs9OnB26htBYY+AChHIs
gDMkUIlKzW
DEBUG: X-OPS-AUTHORIZATION-5: nIIiS4IcSuRwdc+pQIe8TELMnimmXbCEBdm9Q2YddZVdXQbv0p
SGvh60qtYJ
DEBUG: X-OPS-AUTHORIZATION-6: r0v5Egexp/6BdV+U1p3YK1733vrtJYqhrzc8ygPGxw==
DEBUG: HOST: node1:443
DEBUG: X-REMOTE-REQUEST-ID: 0843d3df-b079-41c4-b11c-01bd01a294aa
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 404 Object Not Found
DEBUG: server: openresty/1.9.7.2
DEBUG: date: Tue, 02 Aug 2016 22:44:13 GMT
DEBUG: content-type: text/html
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----

DEBUG: ---- End HTTP Response Body -----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot i
dentify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Expected JSON response, but got content-type 'text/html'
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 404 Object Not Found:
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!':
404 "Object Not Found" (Net::HTTPServerException)
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/li
b/chef/http.rb:146:in `request'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/li
b/chef/http.rb:111:in `get'
        from C:/Users/agshah.ORADEV/AppData/Local/chefdk/gem/ruby/2.1.0/gems/kni
fe-push-1.0.1/lib/chef/knife/job_output.rb:35:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/li
b/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/li
b/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/li
b/chef/knife.rb:420:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/li
b/chef/knife.rb:219:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/li
b/chef/application/knife.rb:148:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/bi
n/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:61:in `load'
        from C:/opscode/chefdk/bin/knife:61:in `<main>'

D:\learn-chef\chef-repo>
