### ISSUE TITLE
knife job start --capture option error

### ISSUE THREAD

**Issue by agshah** [chef/knife-push#51]
Hi,
I have opened https://github.com/chef/knife-push/issues/50 for job output not working but now I see that when i use -VV on the job start --capture itself, it gives errors like below. Can someone help to get capture and output work? Its been frustrating so far and I have tried everything I can. New to Chef and hence asking help.

..
DEBUG: ---- HTTP Response Body ----
DEBUG: {"error":"invalid key supplied"}
...
INFO: HTTP Request Returned 400 Bad Request: error
WARNING: Falling back to Push Jobs v1 mode.
...
-------------
D:\learn-chef\chef-repo>knife job start 'iis_stop' 'den01dqg.us.oe.com' -VV
...
INFO: Using configuration from D:/learn-chef/chef-repo/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as agshah
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Using www-proxy.us.oe.com:80 for proxy
DEBUG: Initiating POST to https://den00bza.us.oe.com/organizations/winprod/p
ushy/jobs
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Content-Type: application/json
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: agshah
DEBUG: X-OPS-TIMESTAMP: 2016-08-04T19:17:12Z
DEBUG: X-OPS-CONTENT-HASH: fp9Q3Ao20aAmStutMYtkgfcf4uA=
DEBUG: X-OPS-AUTHORIZATION-1: ke/QVYdbMlvJip1h5kVKap8CUHnPHay5/rBhhDlQYkNWMSfgF6
mvfx2uyho9
DEBUG: X-OPS-AUTHORIZATION-2: tHjPry+r4OGy6yILxqIWfS/cld/xBMPI4/vDYHZT62/5nhftXR
54PdWTq+EQ
DEBUG: X-OPS-AUTHORIZATION-3: 88TNm+dev91UmoFQRYv9kmyA8gf5iYJiKq3KSvewY9zKDKuQJ9
07u4olprzF
DEBUG: X-OPS-AUTHORIZATION-4: skQF2dQbseiBG9MFMSSkPHS/3eXW/+XvSL/wBt9MGtUj0IsUwD
mT1FAVtd/a
DEBUG: X-OPS-AUTHORIZATION-5: ahyFi6d3X1WGLWidd5ws6VTJFJu67UYL+ePBIsJLe05qm4F9Yx
0+00srDtMe
DEBUG: X-OPS-AUTHORIZATION-6: UPuz3J1OvM6Q0VI+NYon+jdgG1gKrsq7YwFXsWdxUw==
DEBUG: HOST: den00bza.us.oe.com:443
DEBUG: X-REMOTE-REQUEST-ID: 22f758e9-1f3c-4c35-ba99-8f2dacd3bafe
DEBUG: Content-Length: 100
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 400 Bad Request
DEBUG: server: openresty/1.9.7.2
DEBUG: date: Thu, 04 Aug 2016 19:17:15 GMT
DEBUG: content-length: 32
DEBUG: connection: close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG: {"error":"invalid key supplied"}
DEBUG: ---- End HTTP Response Body -----
DEBUG: ---- HTTP Request Body ----
DEBUG: {"command":"iis_stop","nodes":["den01dqg.us.oe.com"],"quorum":1,"capt
ure_output":false,"env":{}}
DEBUG: ---- End HTTP Request Body ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Expected JSON response, but got content-type ''
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 400 Bad Request: error
WARNING: Falling back to Push Jobs v1 mode.

**Comment by charlesjohnson** [comment]
`WARNING: Falling back to Push Jobs v1 mode.`

Capture requires Push Jobs server 2, which was just released recently.

https://discourse.chef.io/t/push-jobs-2-1-released/9082

**Comment by victorkotsubinsky** [comment]
I used Push Jobs server version 2, but have same error with knife output command.
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/http.rb:114:in `get': wrong number of arguments (given 3, expected 1..2) (ArgumentError)
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/knife-push-1.0.1/lib/chef/knife/job_output.rb:35:in `run'
